### ISSUE TITLE
Feature `expression bodied members' cannot be used because it is not part of the C# 4.0 language specification

### ISSUE THREAD

**Issue by FullStackForger** [mysticfall/Alensia#1]
Full error
```
Assets/Alensia/Core/Locomotion/AnimatedLocomotion.cs(14,46): error CS1644: Feature `expression bodied members' cannot be used because it is not part of the C# 4.0 language specification
```

One of many errored lines.
```
        public bool UseRootMotionForRotation => _settings.UseRootMotionForRotation;
```

How do I make it work with Unity? Can we have **How to install/run** section in `readme.md` please.

**Comment by mysticfall** [comment]
I didn't realize there'd be anyone interested in actually trying this project so early :)

Anyway, C# 6 is an experimental feature of Unity 2017.1 beta, so you need to upgrade in order to use the feature.

I updated the document to mention this requirement.

**Comment by mysticfall** [comment]
Ok, I'm closing this issue now. You can also ask questions, or make suggestions on the official forum thread here:
https://forum.unity3d.com/threads/alensia-an-open-source-rpg-framework-wanna-be-in-a-very-very-early-stage.465618/
